import 'dart:convert';

class GleaveregisterModelsss {
  String iD;
  String lEAVEYEARID;
  String lEAVENUMBER;
  String lEAVEBECAUSE;
  String lEAVEDATEBEGIN;
  String lEAVEDATEEND;
  String lEAVEDATESUM;
  String dAYTYPEID;
  String lEAVECONTACT;
  String lEAVEDATETIMEREGIS;
  String lEAVETYPECODE;
  String lEAVEPERSONID;
  String lEAVEPERSONCODE;
  String lEAVEPERSONFULLNAME;
  String lEAVEIPADDRESS;
  String lEAVEPOSITIONID;
  String lEAVEDEPARTMENTID;
  String lEAVEDEPARTMENTSUBSUBID;
  String lEAVETYPEPERSONID;
  String lEAVESTATUSCODE;
  String lEAVECONTACTPHONE;
  String lEAVEWORKSEND;
  String lEAVEWORKSENDID;
  String aCCEPTCOMMENT;
  String lEAVECOMMENTBY;
  String lEAVECOMMENTDATETIME;
  String lEAVEACCEPTBY;
  String lEAVEACCEPTDATETIME;
  String rELAXSUM;
  String rELAXPERYEAR;
  String lEAVEORDINATETEMPLE1;
  String lEAVEORDINATETEMPLE2;
  String lEAVEORDINATEADDTEMPLE1;
  String lEAVEORDINATEADDTEMPLE2;
  String lEAVEORDINATESETDATE;
  String lEAVEORDINATESTATUS;
  String lEAVECANCELCOMMENT;
  String lEAVECANCELUSER;
  String lEAVECANCELSTATUS;
  String lEAVECANCELDATETIME;
  String sAVEBYPERSONID;
  String aPPTYPESAVE;
  String dATEBEFORBEGIN;
  String dATEBEFOREND;
  String lEADERPERSONID;
  String lEADERPERSONNAME;
  String dATEBEFORSUM;
  String lEADERPERSONPOSITION;
  String lEADERPOSITIONINWORK;
  String uSERCONFIRMCHECK;
  String lEAVEWORDBEGIN;
  String lEAVEMARRYNAME;
  String lEAVEDATESPAWN;
  String eXITBECAUSE;
  String eXITPOSITIONTYPE;
  String eXITNUMA;
  String eXITNUMB;
  String eXITINDATE;
  String eXITGROUP;
  String eXITPOSITION;
  String eXITWORK;
  String eXITDEP;
  String eXITSECTION;
  String eXITSALARY;
  String eXITYEAR;
  String eXITMONTH;
  String eXITDATEBEGIN;
  String eXITDATEFINISH;
  String eXITPERSONVCODE;
  String oDEINTEMPLE;
  String oDEINTEMPLEADD;
  String oDEINTEMPLEPHONE;
  String oDEINDATE;
  String oDENTEMPLELIVE;
  String oDENTEMPLELIVEADD;
  String oDENEVER;
  String aRMYBY;
  String aRMYNUM;
  String aRMYDATE;
  String aRMYVISIT;
  String aRMYVISITADD;
  String eDUSUBJECT;
  String eDUBRANCH;
  String eDUACADEMY;
  String eDUCONTRYID;
  String eDUTON;
  String eDUTCOURSE;
  String eDUTLOCATION;
  String eDUTCONTRYID;
  String eDUTTON;
  String eDUTYPE;
  String eDUT01;
  String eDUT02;
  String eDUT03;
  String lEAVECANCELREQUEST;
  String lEAVECANCELREQUESTDATE;
  String lEAVEPERSONLAVELNAME;
  String lEAVEPERSONLAVELID;
  String lEADERDEPPERSONID;
  String lEADERDEPPERSONNAME;
  String lEADERDEPPERSONPOSITION;
  String lOCATIONID;
  String lOCATIONNAME;
  String lEAVETYPENAME;
  String wORKDO;
  String lEAVESUMALL;
  String lEAVESUMHOLIDAY;
  String lEAVESUMSETSUN;
  String oDENTYPE;
  String eDUKIND;
  String fWMARRY;
  String fWMARRYPOSITION;
  String fWMARRYLEVEL;
  String fWMARRYUNDER;
  String fWCOUNTRYID;
  String fWMARRYSALARY;
  String uSERCONFIRMCHECKID;
  String lEAVEACCEPTBYID;
  String tOPLEADERACID;
  String tOPLEADERACNAME;
  String tOPLEADERACCMD;
  String uSERCONFIRMCHECKDATE;
  String tOPLEADERACDATE;
  String tOPLEADERACDATETIME;
  String rEASONTYPEID;
  String updatedAt;
  String createdAt;
  String eXITPERSONVCODEDATE;
  String dATEOFF;
  String cONFIRMCHECKDATE;
  String lEAVEPOSITIONDATE;
  String lEAVEBALANCEDATE;
  GleaveregisterModelsss({
    required this.iD,
    required this.lEAVEYEARID,
    required this.lEAVENUMBER,
    required this.lEAVEBECAUSE,
    required this.lEAVEDATEBEGIN,
    required this.lEAVEDATEEND,
    required this.lEAVEDATESUM,
    required this.dAYTYPEID,
    required this.lEAVECONTACT,
    required this.lEAVEDATETIMEREGIS,
    required this.lEAVETYPECODE,
    required this.lEAVEPERSONID,
    required this.lEAVEPERSONCODE,
    required this.lEAVEPERSONFULLNAME,
    required this.lEAVEIPADDRESS,
    required this.lEAVEPOSITIONID,
    required this.lEAVEDEPARTMENTID,
    required this.lEAVEDEPARTMENTSUBSUBID,
    required this.lEAVETYPEPERSONID,
    required this.lEAVESTATUSCODE,
    required this.lEAVECONTACTPHONE,
    required this.lEAVEWORKSEND,
    required this.lEAVEWORKSENDID,
    required this.aCCEPTCOMMENT,
    required this.lEAVECOMMENTBY,
    required this.lEAVECOMMENTDATETIME,
    required this.lEAVEACCEPTBY,
    required this.lEAVEACCEPTDATETIME,
    required this.rELAXSUM,
    required this.rELAXPERYEAR,
    required this.lEAVEORDINATETEMPLE1,
    required this.lEAVEORDINATETEMPLE2,
    required this.lEAVEORDINATEADDTEMPLE1,
    required this.lEAVEORDINATEADDTEMPLE2,
    required this.lEAVEORDINATESETDATE,
    required this.lEAVEORDINATESTATUS,
    required this.lEAVECANCELCOMMENT,
    required this.lEAVECANCELUSER,
    required this.lEAVECANCELSTATUS,
    required this.lEAVECANCELDATETIME,
    required this.sAVEBYPERSONID,
    required this.aPPTYPESAVE,
    required this.dATEBEFORBEGIN,
    required this.dATEBEFOREND,
    required this.lEADERPERSONID,
    required this.lEADERPERSONNAME,
    required this.dATEBEFORSUM,
    required this.lEADERPERSONPOSITION,
    required this.lEADERPOSITIONINWORK,
    required this.uSERCONFIRMCHECK,
    required this.lEAVEWORDBEGIN,
    required this.lEAVEMARRYNAME,
    required this.lEAVEDATESPAWN,
    required this.eXITBECAUSE,
    required this.eXITPOSITIONTYPE,
    required this.eXITNUMA,
    required this.eXITNUMB,
    required this.eXITINDATE,
    required this.eXITGROUP,
    required this.eXITPOSITION,
    required this.eXITWORK,
    required this.eXITDEP,
    required this.eXITSECTION,
    required this.eXITSALARY,
    required this.eXITYEAR,
    required this.eXITMONTH,
    required this.eXITDATEBEGIN,
    required this.eXITDATEFINISH,
    required this.eXITPERSONVCODE,
    required this.oDEINTEMPLE,
    required this.oDEINTEMPLEADD,
    required this.oDEINTEMPLEPHONE,
    required this.oDEINDATE,
    required this.oDENTEMPLELIVE,
    required this.oDENTEMPLELIVEADD,
    required this.oDENEVER,
    required this.aRMYBY,
    required this.aRMYNUM,
    required this.aRMYDATE,
    required this.aRMYVISIT,
    required this.aRMYVISITADD,
    required this.eDUSUBJECT,
    required this.eDUBRANCH,
    required this.eDUACADEMY,
    required this.eDUCONTRYID,
    required this.eDUTON,
    required this.eDUTCOURSE,
    required this.eDUTLOCATION,
    required this.eDUTCONTRYID,
    required this.eDUTTON,
    required this.eDUTYPE,
    required this.eDUT01,
    required this.eDUT02,
    required this.eDUT03,
    required this.lEAVECANCELREQUEST,
    required this.lEAVECANCELREQUESTDATE,
    required this.lEAVEPERSONLAVELNAME,
    required this.lEAVEPERSONLAVELID,
    required this.lEADERDEPPERSONID,
    required this.lEADERDEPPERSONNAME,
    required this.lEADERDEPPERSONPOSITION,
    required this.lOCATIONID,
    required this.lOCATIONNAME,
    required this.lEAVETYPENAME,
    required this.wORKDO,
    required this.lEAVESUMALL,
    required this.lEAVESUMHOLIDAY,
    required this.lEAVESUMSETSUN,
    required this.oDENTYPE,
    required this.eDUKIND,
    required this.fWMARRY,
    required this.fWMARRYPOSITION,
    required this.fWMARRYLEVEL,
    required this.fWMARRYUNDER,
    required this.fWCOUNTRYID,
    required this.fWMARRYSALARY,
    required this.uSERCONFIRMCHECKID,
    required this.lEAVEACCEPTBYID,
    required this.tOPLEADERACID,
    required this.tOPLEADERACNAME,
    required this.tOPLEADERACCMD,
    required this.uSERCONFIRMCHECKDATE,
    required this.tOPLEADERACDATE,
    required this.tOPLEADERACDATETIME,
    required this.rEASONTYPEID,
    required this.updatedAt,
    required this.createdAt,
    required this.eXITPERSONVCODEDATE,
    required this.dATEOFF,
    required this.cONFIRMCHECKDATE,
    required this.lEAVEPOSITIONDATE,
    required this.lEAVEBALANCEDATE,
  });

  GleaveregisterModelsss copyWith({
    String? iD,
    String? lEAVEYEARID,
    String? lEAVENUMBER,
    String? lEAVEBECAUSE,
    String? lEAVEDATEBEGIN,
    String? lEAVEDATEEND,
    String? lEAVEDATESUM,
    String? dAYTYPEID,
    String? lEAVECONTACT,
    String? lEAVEDATETIMEREGIS,
    String? lEAVETYPECODE,
    String? lEAVEPERSONID,
    String? lEAVEPERSONCODE,
    String? lEAVEPERSONFULLNAME,
    String? lEAVEIPADDRESS,
    String? lEAVEPOSITIONID,
    String? lEAVEDEPARTMENTID,
    String? lEAVEDEPARTMENTSUBSUBID,
    String? lEAVETYPEPERSONID,
    String? lEAVESTATUSCODE,
    String? lEAVECONTACTPHONE,
    String? lEAVEWORKSEND,
    String? lEAVEWORKSENDID,
    String? aCCEPTCOMMENT,
    String? lEAVECOMMENTBY,
    String? lEAVECOMMENTDATETIME,
    String? lEAVEACCEPTBY,
    String? lEAVEACCEPTDATETIME,
    String? rELAXSUM,
    String? rELAXPERYEAR,
    String? lEAVEORDINATETEMPLE1,
    String? lEAVEORDINATETEMPLE2,
    String? lEAVEORDINATEADDTEMPLE1,
    String? lEAVEORDINATEADDTEMPLE2,
    String? lEAVEORDINATESETDATE,
    String? lEAVEORDINATESTATUS,
    String? lEAVECANCELCOMMENT,
    String? lEAVECANCELUSER,
    String? lEAVECANCELSTATUS,
    String? lEAVECANCELDATETIME,
    String? sAVEBYPERSONID,
    String? aPPTYPESAVE,
    String? dATEBEFORBEGIN,
    String? dATEBEFOREND,
    String? lEADERPERSONID,
    String? lEADERPERSONNAME,
    String? dATEBEFORSUM,
    String? lEADERPERSONPOSITION,
    String? lEADERPOSITIONINWORK,
    String? uSERCONFIRMCHECK,
    String? lEAVEWORDBEGIN,
    String? lEAVEMARRYNAME,
    String? lEAVEDATESPAWN,
    String? eXITBECAUSE,
    String? eXITPOSITIONTYPE,
    String? eXITNUMA,
    String? eXITNUMB,
    String? eXITINDATE,
    String? eXITGROUP,
    String? eXITPOSITION,
    String? eXITWORK,
    String? eXITDEP,
    String? eXITSECTION,
    String? eXITSALARY,
    String? eXITYEAR,
    String? eXITMONTH,
    String? eXITDATEBEGIN,
    String? eXITDATEFINISH,
    String? eXITPERSONVCODE,
    String? oDEINTEMPLE,
    String? oDEINTEMPLEADD,
    String? oDEINTEMPLEPHONE,
    String? oDEINDATE,
    String? oDENTEMPLELIVE,
    String? oDENTEMPLELIVEADD,
    String? oDENEVER,
    String? aRMYBY,
    String? aRMYNUM,
    String? aRMYDATE,
    String? aRMYVISIT,
    String? aRMYVISITADD,
    String? eDUSUBJECT,
    String? eDUBRANCH,
    String? eDUACADEMY,
    String? eDUCONTRYID,
    String? eDUTON,
    String? eDUTCOURSE,
    String? eDUTLOCATION,
    String? eDUTCONTRYID,
    String? eDUTTON,
    String? eDUTYPE,
    String? eDUT01,
    String? eDUT02,
    String? eDUT03,
    String? lEAVECANCELREQUEST,
    String? lEAVECANCELREQUESTDATE,
    String? lEAVEPERSONLAVELNAME,
    String? lEAVEPERSONLAVELID,
    String? lEADERDEPPERSONID,
    String? lEADERDEPPERSONNAME,
    String? lEADERDEPPERSONPOSITION,
    String? lOCATIONID,
    String? lOCATIONNAME,
    String? lEAVETYPENAME,
    String? wORKDO,
    String? lEAVESUMALL,
    String? lEAVESUMHOLIDAY,
    String? lEAVESUMSETSUN,
    String? oDENTYPE,
    String? eDUKIND,
    String? fWMARRY,
    String? fWMARRYPOSITION,
    String? fWMARRYLEVEL,
    String? fWMARRYUNDER,
    String? fWCOUNTRYID,
    String? fWMARRYSALARY,
    String? uSERCONFIRMCHECKID,
    String? lEAVEACCEPTBYID,
    String? tOPLEADERACID,
    String? tOPLEADERACNAME,
    String? tOPLEADERACCMD,
    String? uSERCONFIRMCHECKDATE,
    String? tOPLEADERACDATE,
    String? tOPLEADERACDATETIME,
    String? rEASONTYPEID,
    String? updatedAt,
    String? createdAt,
    String? eXITPERSONVCODEDATE,
    String? dATEOFF,
    String? cONFIRMCHECKDATE,
    String? lEAVEPOSITIONDATE,
    String? lEAVEBALANCEDATE,
  }) {
    return GleaveregisterModelsss(
      iD: iD ?? this.iD,
      lEAVEYEARID: lEAVEYEARID ?? this.lEAVEYEARID,
      lEAVENUMBER: lEAVENUMBER ?? this.lEAVENUMBER,
      lEAVEBECAUSE: lEAVEBECAUSE ?? this.lEAVEBECAUSE,
      lEAVEDATEBEGIN: lEAVEDATEBEGIN ?? this.lEAVEDATEBEGIN,
      lEAVEDATEEND: lEAVEDATEEND ?? this.lEAVEDATEEND,
      lEAVEDATESUM: lEAVEDATESUM ?? this.lEAVEDATESUM,
      dAYTYPEID: dAYTYPEID ?? this.dAYTYPEID,
      lEAVECONTACT: lEAVECONTACT ?? this.lEAVECONTACT,
      lEAVEDATETIMEREGIS: lEAVEDATETIMEREGIS ?? this.lEAVEDATETIMEREGIS,
      lEAVETYPECODE: lEAVETYPECODE ?? this.lEAVETYPECODE,
      lEAVEPERSONID: lEAVEPERSONID ?? this.lEAVEPERSONID,
      lEAVEPERSONCODE: lEAVEPERSONCODE ?? this.lEAVEPERSONCODE,
      lEAVEPERSONFULLNAME: lEAVEPERSONFULLNAME ?? this.lEAVEPERSONFULLNAME,
      lEAVEIPADDRESS: lEAVEIPADDRESS ?? this.lEAVEIPADDRESS,
      lEAVEPOSITIONID: lEAVEPOSITIONID ?? this.lEAVEPOSITIONID,
      lEAVEDEPARTMENTID: lEAVEDEPARTMENTID ?? this.lEAVEDEPARTMENTID,
      lEAVEDEPARTMENTSUBSUBID: lEAVEDEPARTMENTSUBSUBID ?? this.lEAVEDEPARTMENTSUBSUBID,
      lEAVETYPEPERSONID: lEAVETYPEPERSONID ?? this.lEAVETYPEPERSONID,
      lEAVESTATUSCODE: lEAVESTATUSCODE ?? this.lEAVESTATUSCODE,
      lEAVECONTACTPHONE: lEAVECONTACTPHONE ?? this.lEAVECONTACTPHONE,
      lEAVEWORKSEND: lEAVEWORKSEND ?? this.lEAVEWORKSEND,
      lEAVEWORKSENDID: lEAVEWORKSENDID ?? this.lEAVEWORKSENDID,
      aCCEPTCOMMENT: aCCEPTCOMMENT ?? this.aCCEPTCOMMENT,
      lEAVECOMMENTBY: lEAVECOMMENTBY ?? this.lEAVECOMMENTBY,
      lEAVECOMMENTDATETIME: lEAVECOMMENTDATETIME ?? this.lEAVECOMMENTDATETIME,
      lEAVEACCEPTBY: lEAVEACCEPTBY ?? this.lEAVEACCEPTBY,
      lEAVEACCEPTDATETIME: lEAVEACCEPTDATETIME ?? this.lEAVEACCEPTDATETIME,
      rELAXSUM: rELAXSUM ?? this.rELAXSUM,
      rELAXPERYEAR: rELAXPERYEAR ?? this.rELAXPERYEAR,
      lEAVEORDINATETEMPLE1: lEAVEORDINATETEMPLE1 ?? this.lEAVEORDINATETEMPLE1,
      lEAVEORDINATETEMPLE2: lEAVEORDINATETEMPLE2 ?? this.lEAVEORDINATETEMPLE2,
      lEAVEORDINATEADDTEMPLE1: lEAVEORDINATEADDTEMPLE1 ?? this.lEAVEORDINATEADDTEMPLE1,
      lEAVEORDINATEADDTEMPLE2: lEAVEORDINATEADDTEMPLE2 ?? this.lEAVEORDINATEADDTEMPLE2,
      lEAVEORDINATESETDATE: lEAVEORDINATESETDATE ?? this.lEAVEORDINATESETDATE,
      lEAVEORDINATESTATUS: lEAVEORDINATESTATUS ?? this.lEAVEORDINATESTATUS,
      lEAVECANCELCOMMENT: lEAVECANCELCOMMENT ?? this.lEAVECANCELCOMMENT,
      lEAVECANCELUSER: lEAVECANCELUSER ?? this.lEAVECANCELUSER,
      lEAVECANCELSTATUS: lEAVECANCELSTATUS ?? this.lEAVECANCELSTATUS,
      lEAVECANCELDATETIME: lEAVECANCELDATETIME ?? this.lEAVECANCELDATETIME,
      sAVEBYPERSONID: sAVEBYPERSONID ?? this.sAVEBYPERSONID,
      aPPTYPESAVE: aPPTYPESAVE ?? this.aPPTYPESAVE,
      dATEBEFORBEGIN: dATEBEFORBEGIN ?? this.dATEBEFORBEGIN,
      dATEBEFOREND: dATEBEFOREND ?? this.dATEBEFOREND,
      lEADERPERSONID: lEADERPERSONID ?? this.lEADERPERSONID,
      lEADERPERSONNAME: lEADERPERSONNAME ?? this.lEADERPERSONNAME,
      dATEBEFORSUM: dATEBEFORSUM ?? this.dATEBEFORSUM,
      lEADERPERSONPOSITION: lEADERPERSONPOSITION ?? this.lEADERPERSONPOSITION,
      lEADERPOSITIONINWORK: lEADERPOSITIONINWORK ?? this.lEADERPOSITIONINWORK,
      uSERCONFIRMCHECK: uSERCONFIRMCHECK ?? this.uSERCONFIRMCHECK,
      lEAVEWORDBEGIN: lEAVEWORDBEGIN ?? this.lEAVEWORDBEGIN,
      lEAVEMARRYNAME: lEAVEMARRYNAME ?? this.lEAVEMARRYNAME,
      lEAVEDATESPAWN: lEAVEDATESPAWN ?? this.lEAVEDATESPAWN,
      eXITBECAUSE: eXITBECAUSE ?? this.eXITBECAUSE,
      eXITPOSITIONTYPE: eXITPOSITIONTYPE ?? this.eXITPOSITIONTYPE,
      eXITNUMA: eXITNUMA ?? this.eXITNUMA,
      eXITNUMB: eXITNUMB ?? this.eXITNUMB,
      eXITINDATE: eXITINDATE ?? this.eXITINDATE,
      eXITGROUP: eXITGROUP ?? this.eXITGROUP,
      eXITPOSITION: eXITPOSITION ?? this.eXITPOSITION,
      eXITWORK: eXITWORK ?? this.eXITWORK,
      eXITDEP: eXITDEP ?? this.eXITDEP,
      eXITSECTION: eXITSECTION ?? this.eXITSECTION,
      eXITSALARY: eXITSALARY ?? this.eXITSALARY,
      eXITYEAR: eXITYEAR ?? this.eXITYEAR,
      eXITMONTH: eXITMONTH ?? this.eXITMONTH,
      eXITDATEBEGIN: eXITDATEBEGIN ?? this.eXITDATEBEGIN,
      eXITDATEFINISH: eXITDATEFINISH ?? this.eXITDATEFINISH,
      eXITPERSONVCODE: eXITPERSONVCODE ?? this.eXITPERSONVCODE,
      oDEINTEMPLE: oDEINTEMPLE ?? this.oDEINTEMPLE,
      oDEINTEMPLEADD: oDEINTEMPLEADD ?? this.oDEINTEMPLEADD,
      oDEINTEMPLEPHONE: oDEINTEMPLEPHONE ?? this.oDEINTEMPLEPHONE,
      oDEINDATE: oDEINDATE ?? this.oDEINDATE,
      oDENTEMPLELIVE: oDENTEMPLELIVE ?? this.oDENTEMPLELIVE,
      oDENTEMPLELIVEADD: oDENTEMPLELIVEADD ?? this.oDENTEMPLELIVEADD,
      oDENEVER: oDENEVER ?? this.oDENEVER,
      aRMYBY: aRMYBY ?? this.aRMYBY,
      aRMYNUM: aRMYNUM ?? this.aRMYNUM,
      aRMYDATE: aRMYDATE ?? this.aRMYDATE,
      aRMYVISIT: aRMYVISIT ?? this.aRMYVISIT,
      aRMYVISITADD: aRMYVISITADD ?? this.aRMYVISITADD,
      eDUSUBJECT: eDUSUBJECT ?? this.eDUSUBJECT,
      eDUBRANCH: eDUBRANCH ?? this.eDUBRANCH,
      eDUACADEMY: eDUACADEMY ?? this.eDUACADEMY,
      eDUCONTRYID: eDUCONTRYID ?? this.eDUCONTRYID,
      eDUTON: eDUTON ?? this.eDUTON,
      eDUTCOURSE: eDUTCOURSE ?? this.eDUTCOURSE,
      eDUTLOCATION: eDUTLOCATION ?? this.eDUTLOCATION,
      eDUTCONTRYID: eDUTCONTRYID ?? this.eDUTCONTRYID,
      eDUTTON: eDUTTON ?? this.eDUTTON,
      eDUTYPE: eDUTYPE ?? this.eDUTYPE,
      eDUT01: eDUT01 ?? this.eDUT01,
      eDUT02: eDUT02 ?? this.eDUT02,
      eDUT03: eDUT03 ?? this.eDUT03,
      lEAVECANCELREQUEST: lEAVECANCELREQUEST ?? this.lEAVECANCELREQUEST,
      lEAVECANCELREQUESTDATE: lEAVECANCELREQUESTDATE ?? this.lEAVECANCELREQUESTDATE,
      lEAVEPERSONLAVELNAME: lEAVEPERSONLAVELNAME ?? this.lEAVEPERSONLAVELNAME,
      lEAVEPERSONLAVELID: lEAVEPERSONLAVELID ?? this.lEAVEPERSONLAVELID,
      lEADERDEPPERSONID: lEADERDEPPERSONID ?? this.lEADERDEPPERSONID,
      lEADERDEPPERSONNAME: lEADERDEPPERSONNAME ?? this.lEADERDEPPERSONNAME,
      lEADERDEPPERSONPOSITION: lEADERDEPPERSONPOSITION ?? this.lEADERDEPPERSONPOSITION,
      lOCATIONID: lOCATIONID ?? this.lOCATIONID,
      lOCATIONNAME: lOCATIONNAME ?? this.lOCATIONNAME,
      lEAVETYPENAME: lEAVETYPENAME ?? this.lEAVETYPENAME,
      wORKDO: wORKDO ?? this.wORKDO,
      lEAVESUMALL: lEAVESUMALL ?? this.lEAVESUMALL,
      lEAVESUMHOLIDAY: lEAVESUMHOLIDAY ?? this.lEAVESUMHOLIDAY,
      lEAVESUMSETSUN: lEAVESUMSETSUN ?? this.lEAVESUMSETSUN,
      oDENTYPE: oDENTYPE ?? this.oDENTYPE,
      eDUKIND: eDUKIND ?? this.eDUKIND,
      fWMARRY: fWMARRY ?? this.fWMARRY,
      fWMARRYPOSITION: fWMARRYPOSITION ?? this.fWMARRYPOSITION,
      fWMARRYLEVEL: fWMARRYLEVEL ?? this.fWMARRYLEVEL,
      fWMARRYUNDER: fWMARRYUNDER ?? this.fWMARRYUNDER,
      fWCOUNTRYID: fWCOUNTRYID ?? this.fWCOUNTRYID,
      fWMARRYSALARY: fWMARRYSALARY ?? this.fWMARRYSALARY,
      uSERCONFIRMCHECKID: uSERCONFIRMCHECKID ?? this.uSERCONFIRMCHECKID,
      lEAVEACCEPTBYID: lEAVEACCEPTBYID ?? this.lEAVEACCEPTBYID,
      tOPLEADERACID: tOPLEADERACID ?? this.tOPLEADERACID,
      tOPLEADERACNAME: tOPLEADERACNAME ?? this.tOPLEADERACNAME,
      tOPLEADERACCMD: tOPLEADERACCMD ?? this.tOPLEADERACCMD,
      uSERCONFIRMCHECKDATE: uSERCONFIRMCHECKDATE ?? this.uSERCONFIRMCHECKDATE,
      tOPLEADERACDATE: tOPLEADERACDATE ?? this.tOPLEADERACDATE,
      tOPLEADERACDATETIME: tOPLEADERACDATETIME ?? this.tOPLEADERACDATETIME,
      rEASONTYPEID: rEASONTYPEID ?? this.rEASONTYPEID,
      updatedAt: updatedAt ?? this.updatedAt,
      createdAt: createdAt ?? this.createdAt,
      eXITPERSONVCODEDATE: eXITPERSONVCODEDATE ?? this.eXITPERSONVCODEDATE,
      dATEOFF: dATEOFF ?? this.dATEOFF,
      cONFIRMCHECKDATE: cONFIRMCHECKDATE ?? this.cONFIRMCHECKDATE,
      lEAVEPOSITIONDATE: lEAVEPOSITIONDATE ?? this.lEAVEPOSITIONDATE,
      lEAVEBALANCEDATE: lEAVEBALANCEDATE ?? this.lEAVEBALANCEDATE,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'iD': iD,
      'lEAVEYEARID': lEAVEYEARID,
      'lEAVENUMBER': lEAVENUMBER,
      'lEAVEBECAUSE': lEAVEBECAUSE,
      'lEAVEDATEBEGIN': lEAVEDATEBEGIN,
      'lEAVEDATEEND': lEAVEDATEEND,
      'lEAVEDATESUM': lEAVEDATESUM,
      'dAYTYPEID': dAYTYPEID,
      'lEAVECONTACT': lEAVECONTACT,
      'lEAVEDATETIMEREGIS': lEAVEDATETIMEREGIS,
      'lEAVETYPECODE': lEAVETYPECODE,
      'lEAVEPERSONID': lEAVEPERSONID,
      'lEAVEPERSONCODE': lEAVEPERSONCODE,
      'lEAVEPERSONFULLNAME': lEAVEPERSONFULLNAME,
      'lEAVEIPADDRESS': lEAVEIPADDRESS,
      'lEAVEPOSITIONID': lEAVEPOSITIONID,
      'lEAVEDEPARTMENTID': lEAVEDEPARTMENTID,
      'lEAVEDEPARTMENTSUBSUBID': lEAVEDEPARTMENTSUBSUBID,
      'lEAVETYPEPERSONID': lEAVETYPEPERSONID,
      'lEAVESTATUSCODE': lEAVESTATUSCODE,
      'lEAVECONTACTPHONE': lEAVECONTACTPHONE,
      'lEAVEWORKSEND': lEAVEWORKSEND,
      'lEAVEWORKSENDID': lEAVEWORKSENDID,
      'aCCEPTCOMMENT': aCCEPTCOMMENT,
      'lEAVECOMMENTBY': lEAVECOMMENTBY,
      'lEAVECOMMENTDATETIME': lEAVECOMMENTDATETIME,
      'lEAVEACCEPTBY': lEAVEACCEPTBY,
      'lEAVEACCEPTDATETIME': lEAVEACCEPTDATETIME,
      'rELAXSUM': rELAXSUM,
      'rELAXPERYEAR': rELAXPERYEAR,
      'lEAVEORDINATETEMPLE1': lEAVEORDINATETEMPLE1,
      'lEAVEORDINATETEMPLE2': lEAVEORDINATETEMPLE2,
      'lEAVEORDINATEADDTEMPLE1': lEAVEORDINATEADDTEMPLE1,
      'lEAVEORDINATEADDTEMPLE2': lEAVEORDINATEADDTEMPLE2,
      'lEAVEORDINATESETDATE': lEAVEORDINATESETDATE,
      'lEAVEORDINATESTATUS': lEAVEORDINATESTATUS,
      'lEAVECANCELCOMMENT': lEAVECANCELCOMMENT,
      'lEAVECANCELUSER': lEAVECANCELUSER,
      'lEAVECANCELSTATUS': lEAVECANCELSTATUS,
      'lEAVECANCELDATETIME': lEAVECANCELDATETIME,
      'sAVEBYPERSONID': sAVEBYPERSONID,
      'aPPTYPESAVE': aPPTYPESAVE,
      'dATEBEFORBEGIN': dATEBEFORBEGIN,
      'dATEBEFOREND': dATEBEFOREND,
      'lEADERPERSONID': lEADERPERSONID,
      'lEADERPERSONNAME': lEADERPERSONNAME,
      'dATEBEFORSUM': dATEBEFORSUM,
      'lEADERPERSONPOSITION': lEADERPERSONPOSITION,
      'lEADERPOSITIONINWORK': lEADERPOSITIONINWORK,
      'uSERCONFIRMCHECK': uSERCONFIRMCHECK,
      'lEAVEWORDBEGIN': lEAVEWORDBEGIN,
      'lEAVEMARRYNAME': lEAVEMARRYNAME,
      'lEAVEDATESPAWN': lEAVEDATESPAWN,
      'eXITBECAUSE': eXITBECAUSE,
      'eXITPOSITIONTYPE': eXITPOSITIONTYPE,
      'eXITNUMA': eXITNUMA,
      'eXITNUMB': eXITNUMB,
      'eXITINDATE': eXITINDATE,
      'eXITGROUP': eXITGROUP,
      'eXITPOSITION': eXITPOSITION,
      'eXITWORK': eXITWORK,
      'eXITDEP': eXITDEP,
      'eXITSECTION': eXITSECTION,
      'eXITSALARY': eXITSALARY,
      'eXITYEAR': eXITYEAR,
      'eXITMONTH': eXITMONTH,
      'eXITDATEBEGIN': eXITDATEBEGIN,
      'eXITDATEFINISH': eXITDATEFINISH,
      'eXITPERSONVCODE': eXITPERSONVCODE,
      'oDEINTEMPLE': oDEINTEMPLE,
      'oDEINTEMPLEADD': oDEINTEMPLEADD,
      'oDEINTEMPLEPHONE': oDEINTEMPLEPHONE,
      'oDEINDATE': oDEINDATE,
      'oDENTEMPLELIVE': oDENTEMPLELIVE,
      'oDENTEMPLELIVEADD': oDENTEMPLELIVEADD,
      'oDENEVER': oDENEVER,
      'aRMYBY': aRMYBY,
      'aRMYNUM': aRMYNUM,
      'aRMYDATE': aRMYDATE,
      'aRMYVISIT': aRMYVISIT,
      'aRMYVISITADD': aRMYVISITADD,
      'eDUSUBJECT': eDUSUBJECT,
      'eDUBRANCH': eDUBRANCH,
      'eDUACADEMY': eDUACADEMY,
      'eDUCONTRYID': eDUCONTRYID,
      'eDUTON': eDUTON,
      'eDUTCOURSE': eDUTCOURSE,
      'eDUTLOCATION': eDUTLOCATION,
      'eDUTCONTRYID': eDUTCONTRYID,
      'eDUTTON': eDUTTON,
      'eDUTYPE': eDUTYPE,
      'eDUT01': eDUT01,
      'eDUT02': eDUT02,
      'eDUT03': eDUT03,
      'lEAVECANCELREQUEST': lEAVECANCELREQUEST,
      'lEAVECANCELREQUESTDATE': lEAVECANCELREQUESTDATE,
      'lEAVEPERSONLAVELNAME': lEAVEPERSONLAVELNAME,
      'lEAVEPERSONLAVELID': lEAVEPERSONLAVELID,
      'lEADERDEPPERSONID': lEADERDEPPERSONID,
      'lEADERDEPPERSONNAME': lEADERDEPPERSONNAME,
      'lEADERDEPPERSONPOSITION': lEADERDEPPERSONPOSITION,
      'lOCATIONID': lOCATIONID,
      'lOCATIONNAME': lOCATIONNAME,
      'lEAVETYPENAME': lEAVETYPENAME,
      'wORKDO': wORKDO,
      'lEAVESUMALL': lEAVESUMALL,
      'lEAVESUMHOLIDAY': lEAVESUMHOLIDAY,
      'lEAVESUMSETSUN': lEAVESUMSETSUN,
      'oDENTYPE': oDENTYPE,
      'eDUKIND': eDUKIND,
      'fWMARRY': fWMARRY,
      'fWMARRYPOSITION': fWMARRYPOSITION,
      'fWMARRYLEVEL': fWMARRYLEVEL,
      'fWMARRYUNDER': fWMARRYUNDER,
      'fWCOUNTRYID': fWCOUNTRYID,
      'fWMARRYSALARY': fWMARRYSALARY,
      'uSERCONFIRMCHECKID': uSERCONFIRMCHECKID,
      'lEAVEACCEPTBYID': lEAVEACCEPTBYID,
      'tOPLEADERACID': tOPLEADERACID,
      'tOPLEADERACNAME': tOPLEADERACNAME,
      'tOPLEADERACCMD': tOPLEADERACCMD,
      'uSERCONFIRMCHECKDATE': uSERCONFIRMCHECKDATE,
      'tOPLEADERACDATE': tOPLEADERACDATE,
      'tOPLEADERACDATETIME': tOPLEADERACDATETIME,
      'rEASONTYPEID': rEASONTYPEID,
      'updatedAt': updatedAt,
      'createdAt': createdAt,
      'eXITPERSONVCODEDATE': eXITPERSONVCODEDATE,
      'dATEOFF': dATEOFF,
      'cONFIRMCHECKDATE': cONFIRMCHECKDATE,
      'lEAVEPOSITIONDATE': lEAVEPOSITIONDATE,
      'lEAVEBALANCEDATE': lEAVEBALANCEDATE,
    };
  }

  factory GleaveregisterModelsss.fromMap(Map<String, dynamic> map) {
    return GleaveregisterModelsss(
      iD: map['iD'],
      lEAVEYEARID: map['lEAVEYEARID'],
      lEAVENUMBER: map['lEAVENUMBER'],
      lEAVEBECAUSE: map['lEAVEBECAUSE'],
      lEAVEDATEBEGIN: map['lEAVEDATEBEGIN'],
      lEAVEDATEEND: map['lEAVEDATEEND'],
      lEAVEDATESUM: map['lEAVEDATESUM'],
      dAYTYPEID: map['dAYTYPEID'],
      lEAVECONTACT: map['lEAVECONTACT'],
      lEAVEDATETIMEREGIS: map['lEAVEDATETIMEREGIS'],
      lEAVETYPECODE: map['lEAVETYPECODE'],
      lEAVEPERSONID: map['lEAVEPERSONID'],
      lEAVEPERSONCODE: map['lEAVEPERSONCODE'],
      lEAVEPERSONFULLNAME: map['lEAVEPERSONFULLNAME'],
      lEAVEIPADDRESS: map['lEAVEIPADDRESS'],
      lEAVEPOSITIONID: map['lEAVEPOSITIONID'],
      lEAVEDEPARTMENTID: map['lEAVEDEPARTMENTID'],
      lEAVEDEPARTMENTSUBSUBID: map['lEAVEDEPARTMENTSUBSUBID'],
      lEAVETYPEPERSONID: map['lEAVETYPEPERSONID'],
      lEAVESTATUSCODE: map['lEAVESTATUSCODE'],
      lEAVECONTACTPHONE: map['lEAVECONTACTPHONE'],
      lEAVEWORKSEND: map['lEAVEWORKSEND'],
      lEAVEWORKSENDID: map['lEAVEWORKSENDID'],
      aCCEPTCOMMENT: map['aCCEPTCOMMENT'],
      lEAVECOMMENTBY: map['lEAVECOMMENTBY'],
      lEAVECOMMENTDATETIME: map['lEAVECOMMENTDATETIME'],
      lEAVEACCEPTBY: map['lEAVEACCEPTBY'],
      lEAVEACCEPTDATETIME: map['lEAVEACCEPTDATETIME'],
      rELAXSUM: map['rELAXSUM'],
      rELAXPERYEAR: map['rELAXPERYEAR'],
      lEAVEORDINATETEMPLE1: map['lEAVEORDINATETEMPLE1'],
      lEAVEORDINATETEMPLE2: map['lEAVEORDINATETEMPLE2'],
      lEAVEORDINATEADDTEMPLE1: map['lEAVEORDINATEADDTEMPLE1'],
      lEAVEORDINATEADDTEMPLE2: map['lEAVEORDINATEADDTEMPLE2'],
      lEAVEORDINATESETDATE: map['lEAVEORDINATESETDATE'],
      lEAVEORDINATESTATUS: map['lEAVEORDINATESTATUS'],
      lEAVECANCELCOMMENT: map['lEAVECANCELCOMMENT'],
      lEAVECANCELUSER: map['lEAVECANCELUSER'],
      lEAVECANCELSTATUS: map['lEAVECANCELSTATUS'],
      lEAVECANCELDATETIME: map['lEAVECANCELDATETIME'],
      sAVEBYPERSONID: map['sAVEBYPERSONID'],
      aPPTYPESAVE: map['aPPTYPESAVE'],
      dATEBEFORBEGIN: map['dATEBEFORBEGIN'],
      dATEBEFOREND: map['dATEBEFOREND'],
      lEADERPERSONID: map['lEADERPERSONID'],
      lEADERPERSONNAME: map['lEADERPERSONNAME'],
      dATEBEFORSUM: map['dATEBEFORSUM'],
      lEADERPERSONPOSITION: map['lEADERPERSONPOSITION'],
      lEADERPOSITIONINWORK: map['lEADERPOSITIONINWORK'],
      uSERCONFIRMCHECK: map['uSERCONFIRMCHECK'],
      lEAVEWORDBEGIN: map['lEAVEWORDBEGIN'],
      lEAVEMARRYNAME: map['lEAVEMARRYNAME'],
      lEAVEDATESPAWN: map['lEAVEDATESPAWN'],
      eXITBECAUSE: map['eXITBECAUSE'],
      eXITPOSITIONTYPE: map['eXITPOSITIONTYPE'],
      eXITNUMA: map['eXITNUMA'],
      eXITNUMB: map['eXITNUMB'],
      eXITINDATE: map['eXITINDATE'],
      eXITGROUP: map['eXITGROUP'],
      eXITPOSITION: map['eXITPOSITION'],
      eXITWORK: map['eXITWORK'],
      eXITDEP: map['eXITDEP'],
      eXITSECTION: map['eXITSECTION'],
      eXITSALARY: map['eXITSALARY'],
      eXITYEAR: map['eXITYEAR'],
      eXITMONTH: map['eXITMONTH'],
      eXITDATEBEGIN: map['eXITDATEBEGIN'],
      eXITDATEFINISH: map['eXITDATEFINISH'],
      eXITPERSONVCODE: map['eXITPERSONVCODE'],
      oDEINTEMPLE: map['oDEINTEMPLE'],
      oDEINTEMPLEADD: map['oDEINTEMPLEADD'],
      oDEINTEMPLEPHONE: map['oDEINTEMPLEPHONE'],
      oDEINDATE: map['oDEINDATE'],
      oDENTEMPLELIVE: map['oDENTEMPLELIVE'],
      oDENTEMPLELIVEADD: map['oDENTEMPLELIVEADD'],
      oDENEVER: map['oDENEVER'],
      aRMYBY: map['aRMYBY'],
      aRMYNUM: map['aRMYNUM'],
      aRMYDATE: map['aRMYDATE'],
      aRMYVISIT: map['aRMYVISIT'],
      aRMYVISITADD: map['aRMYVISITADD'],
      eDUSUBJECT: map['eDUSUBJECT'],
      eDUBRANCH: map['eDUBRANCH'],
      eDUACADEMY: map['eDUACADEMY'],
      eDUCONTRYID: map['eDUCONTRYID'],
      eDUTON: map['eDUTON'],
      eDUTCOURSE: map['eDUTCOURSE'],
      eDUTLOCATION: map['eDUTLOCATION'],
      eDUTCONTRYID: map['eDUTCONTRYID'],
      eDUTTON: map['eDUTTON'],
      eDUTYPE: map['eDUTYPE'],
      eDUT01: map['eDUT01'],
      eDUT02: map['eDUT02'],
      eDUT03: map['eDUT03'],
      lEAVECANCELREQUEST: map['lEAVECANCELREQUEST'],
      lEAVECANCELREQUESTDATE: map['lEAVECANCELREQUESTDATE'],
      lEAVEPERSONLAVELNAME: map['lEAVEPERSONLAVELNAME'],
      lEAVEPERSONLAVELID: map['lEAVEPERSONLAVELID'],
      lEADERDEPPERSONID: map['lEADERDEPPERSONID'],
      lEADERDEPPERSONNAME: map['lEADERDEPPERSONNAME'],
      lEADERDEPPERSONPOSITION: map['lEADERDEPPERSONPOSITION'],
      lOCATIONID: map['lOCATIONID'],
      lOCATIONNAME: map['lOCATIONNAME'],
      lEAVETYPENAME: map['lEAVETYPENAME'],
      wORKDO: map['wORKDO'],
      lEAVESUMALL: map['lEAVESUMALL'],
      lEAVESUMHOLIDAY: map['lEAVESUMHOLIDAY'],
      lEAVESUMSETSUN: map['lEAVESUMSETSUN'],
      oDENTYPE: map['oDENTYPE'],
      eDUKIND: map['eDUKIND'],
      fWMARRY: map['fWMARRY'],
      fWMARRYPOSITION: map['fWMARRYPOSITION'],
      fWMARRYLEVEL: map['fWMARRYLEVEL'],
      fWMARRYUNDER: map['fWMARRYUNDER'],
      fWCOUNTRYID: map['fWCOUNTRYID'],
      fWMARRYSALARY: map['fWMARRYSALARY'],
      uSERCONFIRMCHECKID: map['uSERCONFIRMCHECKID'],
      lEAVEACCEPTBYID: map['lEAVEACCEPTBYID'],
      tOPLEADERACID: map['tOPLEADERACID'],
      tOPLEADERACNAME: map['tOPLEADERACNAME'],
      tOPLEADERACCMD: map['tOPLEADERACCMD'],
      uSERCONFIRMCHECKDATE: map['uSERCONFIRMCHECKDATE'],
      tOPLEADERACDATE: map['tOPLEADERACDATE'],
      tOPLEADERACDATETIME: map['tOPLEADERACDATETIME'],
      rEASONTYPEID: map['rEASONTYPEID'],
      updatedAt: map['updatedAt'],
      createdAt: map['createdAt'],
      eXITPERSONVCODEDATE: map['eXITPERSONVCODEDATE'],
      dATEOFF: map['dATEOFF'],
      cONFIRMCHECKDATE: map['cONFIRMCHECKDATE'],
      lEAVEPOSITIONDATE: map['lEAVEPOSITIONDATE'],
      lEAVEBALANCEDATE: map['lEAVEBALANCEDATE'],
    );
  }

  String toJson() => json.encode(toMap());

  factory GleaveregisterModelsss.fromJson(String source) => GleaveregisterModelsss.fromMap(json.decode(source));

  @override
  String toString() {
    return 'GleaveregisterModelsss(iD: $iD, lEAVEYEARID: $lEAVEYEARID, lEAVENUMBER: $lEAVENUMBER, lEAVEBECAUSE: $lEAVEBECAUSE, lEAVEDATEBEGIN: $lEAVEDATEBEGIN, lEAVEDATEEND: $lEAVEDATEEND, lEAVEDATESUM: $lEAVEDATESUM, dAYTYPEID: $dAYTYPEID, lEAVECONTACT: $lEAVECONTACT, lEAVEDATETIMEREGIS: $lEAVEDATETIMEREGIS, lEAVETYPECODE: $lEAVETYPECODE, lEAVEPERSONID: $lEAVEPERSONID, lEAVEPERSONCODE: $lEAVEPERSONCODE, lEAVEPERSONFULLNAME: $lEAVEPERSONFULLNAME, lEAVEIPADDRESS: $lEAVEIPADDRESS, lEAVEPOSITIONID: $lEAVEPOSITIONID, lEAVEDEPARTMENTID: $lEAVEDEPARTMENTID, lEAVEDEPARTMENTSUBSUBID: $lEAVEDEPARTMENTSUBSUBID, lEAVETYPEPERSONID: $lEAVETYPEPERSONID, lEAVESTATUSCODE: $lEAVESTATUSCODE, lEAVECONTACTPHONE: $lEAVECONTACTPHONE, lEAVEWORKSEND: $lEAVEWORKSEND, lEAVEWORKSENDID: $lEAVEWORKSENDID, aCCEPTCOMMENT: $aCCEPTCOMMENT, lEAVECOMMENTBY: $lEAVECOMMENTBY, lEAVECOMMENTDATETIME: $lEAVECOMMENTDATETIME, lEAVEACCEPTBY: $lEAVEACCEPTBY, lEAVEACCEPTDATETIME: $lEAVEACCEPTDATETIME, rELAXSUM: $rELAXSUM, rELAXPERYEAR: $rELAXPERYEAR, lEAVEORDINATETEMPLE1: $lEAVEORDINATETEMPLE1, lEAVEORDINATETEMPLE2: $lEAVEORDINATETEMPLE2, lEAVEORDINATEADDTEMPLE1: $lEAVEORDINATEADDTEMPLE1, lEAVEORDINATEADDTEMPLE2: $lEAVEORDINATEADDTEMPLE2, lEAVEORDINATESETDATE: $lEAVEORDINATESETDATE, lEAVEORDINATESTATUS: $lEAVEORDINATESTATUS, lEAVECANCELCOMMENT: $lEAVECANCELCOMMENT, lEAVECANCELUSER: $lEAVECANCELUSER, lEAVECANCELSTATUS: $lEAVECANCELSTATUS, lEAVECANCELDATETIME: $lEAVECANCELDATETIME, sAVEBYPERSONID: $sAVEBYPERSONID, aPPTYPESAVE: $aPPTYPESAVE, dATEBEFORBEGIN: $dATEBEFORBEGIN, dATEBEFOREND: $dATEBEFOREND, lEADERPERSONID: $lEADERPERSONID, lEADERPERSONNAME: $lEADERPERSONNAME, dATEBEFORSUM: $dATEBEFORSUM, lEADERPERSONPOSITION: $lEADERPERSONPOSITION, lEADERPOSITIONINWORK: $lEADERPOSITIONINWORK, uSERCONFIRMCHECK: $uSERCONFIRMCHECK, lEAVEWORDBEGIN: $lEAVEWORDBEGIN, lEAVEMARRYNAME: $lEAVEMARRYNAME, lEAVEDATESPAWN: $lEAVEDATESPAWN, eXITBECAUSE: $eXITBECAUSE, eXITPOSITIONTYPE: $eXITPOSITIONTYPE, eXITNUMA: $eXITNUMA, eXITNUMB: $eXITNUMB, eXITINDATE: $eXITINDATE, eXITGROUP: $eXITGROUP, eXITPOSITION: $eXITPOSITION, eXITWORK: $eXITWORK, eXITDEP: $eXITDEP, eXITSECTION: $eXITSECTION, eXITSALARY: $eXITSALARY, eXITYEAR: $eXITYEAR, eXITMONTH: $eXITMONTH, eXITDATEBEGIN: $eXITDATEBEGIN, eXITDATEFINISH: $eXITDATEFINISH, eXITPERSONVCODE: $eXITPERSONVCODE, oDEINTEMPLE: $oDEINTEMPLE, oDEINTEMPLEADD: $oDEINTEMPLEADD, oDEINTEMPLEPHONE: $oDEINTEMPLEPHONE, oDEINDATE: $oDEINDATE, oDENTEMPLELIVE: $oDENTEMPLELIVE, oDENTEMPLELIVEADD: $oDENTEMPLELIVEADD, oDENEVER: $oDENEVER, aRMYBY: $aRMYBY, aRMYNUM: $aRMYNUM, aRMYDATE: $aRMYDATE, aRMYVISIT: $aRMYVISIT, aRMYVISITADD: $aRMYVISITADD, eDUSUBJECT: $eDUSUBJECT, eDUBRANCH: $eDUBRANCH, eDUACADEMY: $eDUACADEMY, eDUCONTRYID: $eDUCONTRYID, eDUTON: $eDUTON, eDUTCOURSE: $eDUTCOURSE, eDUTLOCATION: $eDUTLOCATION, eDUTCONTRYID: $eDUTCONTRYID, eDUTTON: $eDUTTON, eDUTYPE: $eDUTYPE, eDUT01: $eDUT01, eDUT02: $eDUT02, eDUT03: $eDUT03, lEAVECANCELREQUEST: $lEAVECANCELREQUEST, lEAVECANCELREQUESTDATE: $lEAVECANCELREQUESTDATE, lEAVEPERSONLAVELNAME: $lEAVEPERSONLAVELNAME, lEAVEPERSONLAVELID: $lEAVEPERSONLAVELID, lEADERDEPPERSONID: $lEADERDEPPERSONID, lEADERDEPPERSONNAME: $lEADERDEPPERSONNAME, lEADERDEPPERSONPOSITION: $lEADERDEPPERSONPOSITION, lOCATIONID: $lOCATIONID, lOCATIONNAME: $lOCATIONNAME, lEAVETYPENAME: $lEAVETYPENAME, wORKDO: $wORKDO, lEAVESUMALL: $lEAVESUMALL, lEAVESUMHOLIDAY: $lEAVESUMHOLIDAY, lEAVESUMSETSUN: $lEAVESUMSETSUN, oDENTYPE: $oDENTYPE, eDUKIND: $eDUKIND, fWMARRY: $fWMARRY, fWMARRYPOSITION: $fWMARRYPOSITION, fWMARRYLEVEL: $fWMARRYLEVEL, fWMARRYUNDER: $fWMARRYUNDER, fWCOUNTRYID: $fWCOUNTRYID, fWMARRYSALARY: $fWMARRYSALARY, uSERCONFIRMCHECKID: $uSERCONFIRMCHECKID, lEAVEACCEPTBYID: $lEAVEACCEPTBYID, tOPLEADERACID: $tOPLEADERACID, tOPLEADERACNAME: $tOPLEADERACNAME, tOPLEADERACCMD: $tOPLEADERACCMD, uSERCONFIRMCHECKDATE: $uSERCONFIRMCHECKDATE, tOPLEADERACDATE: $tOPLEADERACDATE, tOPLEADERACDATETIME: $tOPLEADERACDATETIME, rEASONTYPEID: $rEASONTYPEID, updatedAt: $updatedAt, createdAt: $createdAt, eXITPERSONVCODEDATE: $eXITPERSONVCODEDATE, dATEOFF: $dATEOFF, cONFIRMCHECKDATE: $cONFIRMCHECKDATE, lEAVEPOSITIONDATE: $lEAVEPOSITIONDATE, lEAVEBALANCEDATE: $lEAVEBALANCEDATE)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
  
    return other is GleaveregisterModelsss &&
      other.iD == iD &&
      other.lEAVEYEARID == lEAVEYEARID &&
      other.lEAVENUMBER == lEAVENUMBER &&
      other.lEAVEBECAUSE == lEAVEBECAUSE &&
      other.lEAVEDATEBEGIN == lEAVEDATEBEGIN &&
      other.lEAVEDATEEND == lEAVEDATEEND &&
      other.lEAVEDATESUM == lEAVEDATESUM &&
      other.dAYTYPEID == dAYTYPEID &&
      other.lEAVECONTACT == lEAVECONTACT &&
      other.lEAVEDATETIMEREGIS == lEAVEDATETIMEREGIS &&
      other.lEAVETYPECODE == lEAVETYPECODE &&
      other.lEAVEPERSONID == lEAVEPERSONID &&
      other.lEAVEPERSONCODE == lEAVEPERSONCODE &&
      other.lEAVEPERSONFULLNAME == lEAVEPERSONFULLNAME &&
      other.lEAVEIPADDRESS == lEAVEIPADDRESS &&
      other.lEAVEPOSITIONID == lEAVEPOSITIONID &&
      other.lEAVEDEPARTMENTID == lEAVEDEPARTMENTID &&
      other.lEAVEDEPARTMENTSUBSUBID == lEAVEDEPARTMENTSUBSUBID &&
      other.lEAVETYPEPERSONID == lEAVETYPEPERSONID &&
      other.lEAVESTATUSCODE == lEAVESTATUSCODE &&
      other.lEAVECONTACTPHONE == lEAVECONTACTPHONE &&
      other.lEAVEWORKSEND == lEAVEWORKSEND &&
      other.lEAVEWORKSENDID == lEAVEWORKSENDID &&
      other.aCCEPTCOMMENT == aCCEPTCOMMENT &&
      other.lEAVECOMMENTBY == lEAVECOMMENTBY &&
      other.lEAVECOMMENTDATETIME == lEAVECOMMENTDATETIME &&
      other.lEAVEACCEPTBY == lEAVEACCEPTBY &&
      other.lEAVEACCEPTDATETIME == lEAVEACCEPTDATETIME &&
      other.rELAXSUM == rELAXSUM &&
      other.rELAXPERYEAR == rELAXPERYEAR &&
      other.lEAVEORDINATETEMPLE1 == lEAVEORDINATETEMPLE1 &&
      other.lEAVEORDINATETEMPLE2 == lEAVEORDINATETEMPLE2 &&
      other.lEAVEORDINATEADDTEMPLE1 == lEAVEORDINATEADDTEMPLE1 &&
      other.lEAVEORDINATEADDTEMPLE2 == lEAVEORDINATEADDTEMPLE2 &&
      other.lEAVEORDINATESETDATE == lEAVEORDINATESETDATE &&
      other.lEAVEORDINATESTATUS == lEAVEORDINATESTATUS &&
      other.lEAVECANCELCOMMENT == lEAVECANCELCOMMENT &&
      other.lEAVECANCELUSER == lEAVECANCELUSER &&
      other.lEAVECANCELSTATUS == lEAVECANCELSTATUS &&
      other.lEAVECANCELDATETIME == lEAVECANCELDATETIME &&
      other.sAVEBYPERSONID == sAVEBYPERSONID &&
      other.aPPTYPESAVE == aPPTYPESAVE &&
      other.dATEBEFORBEGIN == dATEBEFORBEGIN &&
      other.dATEBEFOREND == dATEBEFOREND &&
      other.lEADERPERSONID == lEADERPERSONID &&
      other.lEADERPERSONNAME == lEADERPERSONNAME &&
      other.dATEBEFORSUM == dATEBEFORSUM &&
      other.lEADERPERSONPOSITION == lEADERPERSONPOSITION &&
      other.lEADERPOSITIONINWORK == lEADERPOSITIONINWORK &&
      other.uSERCONFIRMCHECK == uSERCONFIRMCHECK &&
      other.lEAVEWORDBEGIN == lEAVEWORDBEGIN &&
      other.lEAVEMARRYNAME == lEAVEMARRYNAME &&
      other.lEAVEDATESPAWN == lEAVEDATESPAWN &&
      other.eXITBECAUSE == eXITBECAUSE &&
      other.eXITPOSITIONTYPE == eXITPOSITIONTYPE &&
      other.eXITNUMA == eXITNUMA &&
      other.eXITNUMB == eXITNUMB &&
      other.eXITINDATE == eXITINDATE &&
      other.eXITGROUP == eXITGROUP &&
      other.eXITPOSITION == eXITPOSITION &&
      other.eXITWORK == eXITWORK &&
      other.eXITDEP == eXITDEP &&
      other.eXITSECTION == eXITSECTION &&
      other.eXITSALARY == eXITSALARY &&
      other.eXITYEAR == eXITYEAR &&
      other.eXITMONTH == eXITMONTH &&
      other.eXITDATEBEGIN == eXITDATEBEGIN &&
      other.eXITDATEFINISH == eXITDATEFINISH &&
      other.eXITPERSONVCODE == eXITPERSONVCODE &&
      other.oDEINTEMPLE == oDEINTEMPLE &&
      other.oDEINTEMPLEADD == oDEINTEMPLEADD &&
      other.oDEINTEMPLEPHONE == oDEINTEMPLEPHONE &&
      other.oDEINDATE == oDEINDATE &&
      other.oDENTEMPLELIVE == oDENTEMPLELIVE &&
      other.oDENTEMPLELIVEADD == oDENTEMPLELIVEADD &&
      other.oDENEVER == oDENEVER &&
      other.aRMYBY == aRMYBY &&
      other.aRMYNUM == aRMYNUM &&
      other.aRMYDATE == aRMYDATE &&
      other.aRMYVISIT == aRMYVISIT &&
      other.aRMYVISITADD == aRMYVISITADD &&
      other.eDUSUBJECT == eDUSUBJECT &&
      other.eDUBRANCH == eDUBRANCH &&
      other.eDUACADEMY == eDUACADEMY &&
      other.eDUCONTRYID == eDUCONTRYID &&
      other.eDUTON == eDUTON &&
      other.eDUTCOURSE == eDUTCOURSE &&
      other.eDUTLOCATION == eDUTLOCATION &&
      other.eDUTCONTRYID == eDUTCONTRYID &&
      other.eDUTTON == eDUTTON &&
      other.eDUTYPE == eDUTYPE &&
      other.eDUT01 == eDUT01 &&
      other.eDUT02 == eDUT02 &&
      other.eDUT03 == eDUT03 &&
      other.lEAVECANCELREQUEST == lEAVECANCELREQUEST &&
      other.lEAVECANCELREQUESTDATE == lEAVECANCELREQUESTDATE &&
      other.lEAVEPERSONLAVELNAME == lEAVEPERSONLAVELNAME &&
      other.lEAVEPERSONLAVELID == lEAVEPERSONLAVELID &&
      other.lEADERDEPPERSONID == lEADERDEPPERSONID &&
      other.lEADERDEPPERSONNAME == lEADERDEPPERSONNAME &&
      other.lEADERDEPPERSONPOSITION == lEADERDEPPERSONPOSITION &&
      other.lOCATIONID == lOCATIONID &&
      other.lOCATIONNAME == lOCATIONNAME &&
      other.lEAVETYPENAME == lEAVETYPENAME &&
      other.wORKDO == wORKDO &&
      other.lEAVESUMALL == lEAVESUMALL &&
      other.lEAVESUMHOLIDAY == lEAVESUMHOLIDAY &&
      other.lEAVESUMSETSUN == lEAVESUMSETSUN &&
      other.oDENTYPE == oDENTYPE &&
      other.eDUKIND == eDUKIND &&
      other.fWMARRY == fWMARRY &&
      other.fWMARRYPOSITION == fWMARRYPOSITION &&
      other.fWMARRYLEVEL == fWMARRYLEVEL &&
      other.fWMARRYUNDER == fWMARRYUNDER &&
      other.fWCOUNTRYID == fWCOUNTRYID &&
      other.fWMARRYSALARY == fWMARRYSALARY &&
      other.uSERCONFIRMCHECKID == uSERCONFIRMCHECKID &&
      other.lEAVEACCEPTBYID == lEAVEACCEPTBYID &&
      other.tOPLEADERACID == tOPLEADERACID &&
      other.tOPLEADERACNAME == tOPLEADERACNAME &&
      other.tOPLEADERACCMD == tOPLEADERACCMD &&
      other.uSERCONFIRMCHECKDATE == uSERCONFIRMCHECKDATE &&
      other.tOPLEADERACDATE == tOPLEADERACDATE &&
      other.tOPLEADERACDATETIME == tOPLEADERACDATETIME &&
      other.rEASONTYPEID == rEASONTYPEID &&
      other.updatedAt == updatedAt &&
      other.createdAt == createdAt &&
      other.eXITPERSONVCODEDATE == eXITPERSONVCODEDATE &&
      other.dATEOFF == dATEOFF &&
      other.cONFIRMCHECKDATE == cONFIRMCHECKDATE &&
      other.lEAVEPOSITIONDATE == lEAVEPOSITIONDATE &&
      other.lEAVEBALANCEDATE == lEAVEBALANCEDATE;
  }

  @override
  int get hashCode {
    return iD.hashCode ^
      lEAVEYEARID.hashCode ^
      lEAVENUMBER.hashCode ^
      lEAVEBECAUSE.hashCode ^
      lEAVEDATEBEGIN.hashCode ^
      lEAVEDATEEND.hashCode ^
      lEAVEDATESUM.hashCode ^
      dAYTYPEID.hashCode ^
      lEAVECONTACT.hashCode ^
      lEAVEDATETIMEREGIS.hashCode ^
      lEAVETYPECODE.hashCode ^
      lEAVEPERSONID.hashCode ^
      lEAVEPERSONCODE.hashCode ^
      lEAVEPERSONFULLNAME.hashCode ^
      lEAVEIPADDRESS.hashCode ^
      lEAVEPOSITIONID.hashCode ^
      lEAVEDEPARTMENTID.hashCode ^
      lEAVEDEPARTMENTSUBSUBID.hashCode ^
      lEAVETYPEPERSONID.hashCode ^
      lEAVESTATUSCODE.hashCode ^
      lEAVECONTACTPHONE.hashCode ^
      lEAVEWORKSEND.hashCode ^
      lEAVEWORKSENDID.hashCode ^
      aCCEPTCOMMENT.hashCode ^
      lEAVECOMMENTBY.hashCode ^
      lEAVECOMMENTDATETIME.hashCode ^
      lEAVEACCEPTBY.hashCode ^
      lEAVEACCEPTDATETIME.hashCode ^
      rELAXSUM.hashCode ^
      rELAXPERYEAR.hashCode ^
      lEAVEORDINATETEMPLE1.hashCode ^
      lEAVEORDINATETEMPLE2.hashCode ^
      lEAVEORDINATEADDTEMPLE1.hashCode ^
      lEAVEORDINATEADDTEMPLE2.hashCode ^
      lEAVEORDINATESETDATE.hashCode ^
      lEAVEORDINATESTATUS.hashCode ^
      lEAVECANCELCOMMENT.hashCode ^
      lEAVECANCELUSER.hashCode ^
      lEAVECANCELSTATUS.hashCode ^
      lEAVECANCELDATETIME.hashCode ^
      sAVEBYPERSONID.hashCode ^
      aPPTYPESAVE.hashCode ^
      dATEBEFORBEGIN.hashCode ^
      dATEBEFOREND.hashCode ^
      lEADERPERSONID.hashCode ^
      lEADERPERSONNAME.hashCode ^
      dATEBEFORSUM.hashCode ^
      lEADERPERSONPOSITION.hashCode ^
      lEADERPOSITIONINWORK.hashCode ^
      uSERCONFIRMCHECK.hashCode ^
      lEAVEWORDBEGIN.hashCode ^
      lEAVEMARRYNAME.hashCode ^
      lEAVEDATESPAWN.hashCode ^
      eXITBECAUSE.hashCode ^
      eXITPOSITIONTYPE.hashCode ^
      eXITNUMA.hashCode ^
      eXITNUMB.hashCode ^
      eXITINDATE.hashCode ^
      eXITGROUP.hashCode ^
      eXITPOSITION.hashCode ^
      eXITWORK.hashCode ^
      eXITDEP.hashCode ^
      eXITSECTION.hashCode ^
      eXITSALARY.hashCode ^
      eXITYEAR.hashCode ^
      eXITMONTH.hashCode ^
      eXITDATEBEGIN.hashCode ^
      eXITDATEFINISH.hashCode ^
      eXITPERSONVCODE.hashCode ^
      oDEINTEMPLE.hashCode ^
      oDEINTEMPLEADD.hashCode ^
      oDEINTEMPLEPHONE.hashCode ^
      oDEINDATE.hashCode ^
      oDENTEMPLELIVE.hashCode ^
      oDENTEMPLELIVEADD.hashCode ^
      oDENEVER.hashCode ^
      aRMYBY.hashCode ^
      aRMYNUM.hashCode ^
      aRMYDATE.hashCode ^
      aRMYVISIT.hashCode ^
      aRMYVISITADD.hashCode ^
      eDUSUBJECT.hashCode ^
      eDUBRANCH.hashCode ^
      eDUACADEMY.hashCode ^
      eDUCONTRYID.hashCode ^
      eDUTON.hashCode ^
      eDUTCOURSE.hashCode ^
      eDUTLOCATION.hashCode ^
      eDUTCONTRYID.hashCode ^
      eDUTTON.hashCode ^
      eDUTYPE.hashCode ^
      eDUT01.hashCode ^
      eDUT02.hashCode ^
      eDUT03.hashCode ^
      lEAVECANCELREQUEST.hashCode ^
      lEAVECANCELREQUESTDATE.hashCode ^
      lEAVEPERSONLAVELNAME.hashCode ^
      lEAVEPERSONLAVELID.hashCode ^
      lEADERDEPPERSONID.hashCode ^
      lEADERDEPPERSONNAME.hashCode ^
      lEADERDEPPERSONPOSITION.hashCode ^
      lOCATIONID.hashCode ^
      lOCATIONNAME.hashCode ^
      lEAVETYPENAME.hashCode ^
      wORKDO.hashCode ^
      lEAVESUMALL.hashCode ^
      lEAVESUMHOLIDAY.hashCode ^
      lEAVESUMSETSUN.hashCode ^
      oDENTYPE.hashCode ^
      eDUKIND.hashCode ^
      fWMARRY.hashCode ^
      fWMARRYPOSITION.hashCode ^
      fWMARRYLEVEL.hashCode ^
      fWMARRYUNDER.hashCode ^
      fWCOUNTRYID.hashCode ^
      fWMARRYSALARY.hashCode ^
      uSERCONFIRMCHECKID.hashCode ^
      lEAVEACCEPTBYID.hashCode ^
      tOPLEADERACID.hashCode ^
      tOPLEADERACNAME.hashCode ^
      tOPLEADERACCMD.hashCode ^
      uSERCONFIRMCHECKDATE.hashCode ^
      tOPLEADERACDATE.hashCode ^
      tOPLEADERACDATETIME.hashCode ^
      rEASONTYPEID.hashCode ^
      updatedAt.hashCode ^
      createdAt.hashCode ^
      eXITPERSONVCODEDATE.hashCode ^
      dATEOFF.hashCode ^
      cONFIRMCHECKDATE.hashCode ^
      lEAVEPOSITIONDATE.hashCode ^
      lEAVEBALANCEDATE.hashCode;
  }
}
