import 'dart:convert';

class WarehouseModel {
  final String WAREHOUSE_ID;
  final String WAREHOUSE_REQUEST_CODE;
  final String WAREHOUSE_DATE_WANT;
  final String WAREHOUSE_SAVE_HR_ID;
  final String WAREHOUSE_SAVE_HR_NAME;
  final String WAREHOUSE_SAVE_HR_POSITION;
  final String WAREHOUSE_SAVE_HR_DEP_SUB_NAME;
  final String WAREHOUSE_STATUS;
  final String WAREHOUSE_AGREE_HR_ID;
  final String WAREHOUSE_AGREE_HR_NAME;
  final String WAREHOUSE_REQUEST_BUY_COMMENT;
  final String WAREHOUSE_BUDGET_YEAR;
  final String WAREHOUSE_INVEN_ID;
  final String INVEN_NAME;
  WarehouseModel({
    required this.WAREHOUSE_ID,
    required this.WAREHOUSE_REQUEST_CODE,
    required this.WAREHOUSE_DATE_WANT,
    required this.WAREHOUSE_SAVE_HR_ID,
    required this.WAREHOUSE_SAVE_HR_NAME,
    required this.WAREHOUSE_SAVE_HR_POSITION,
    required this.WAREHOUSE_SAVE_HR_DEP_SUB_NAME,
    required this.WAREHOUSE_STATUS,
    required this.WAREHOUSE_AGREE_HR_ID,
    required this.WAREHOUSE_AGREE_HR_NAME,
    required this.WAREHOUSE_REQUEST_BUY_COMMENT,
    required this.WAREHOUSE_BUDGET_YEAR,
    required this.WAREHOUSE_INVEN_ID,
    required this.INVEN_NAME,
  });

  WarehouseModel copyWith({
    String? WAREHOUSE_ID,
    String? WAREHOUSE_REQUEST_CODE,
    String? WAREHOUSE_DATE_WANT,
    String? WAREHOUSE_SAVE_HR_ID,
    String? WAREHOUSE_SAVE_HR_NAME,
    String? WAREHOUSE_SAVE_HR_POSITION,
    String? WAREHOUSE_SAVE_HR_DEP_SUB_NAME,
    String? WAREHOUSE_STATUS,
    String? WAREHOUSE_AGREE_HR_ID,
    String? WAREHOUSE_AGREE_HR_NAME,
    String? WAREHOUSE_REQUEST_BUY_COMMENT,
    String? WAREHOUSE_BUDGET_YEAR,
    String? WAREHOUSE_INVEN_ID,
    String? INVEN_NAME,
  }) {
    return WarehouseModel(
      WAREHOUSE_ID: WAREHOUSE_ID ?? this.WAREHOUSE_ID,
      WAREHOUSE_REQUEST_CODE:
          WAREHOUSE_REQUEST_CODE ?? this.WAREHOUSE_REQUEST_CODE,
      WAREHOUSE_DATE_WANT: WAREHOUSE_DATE_WANT ?? this.WAREHOUSE_DATE_WANT,
      WAREHOUSE_SAVE_HR_ID: WAREHOUSE_SAVE_HR_ID ?? this.WAREHOUSE_SAVE_HR_ID,
      WAREHOUSE_SAVE_HR_NAME:
          WAREHOUSE_SAVE_HR_NAME ?? this.WAREHOUSE_SAVE_HR_NAME,
      WAREHOUSE_SAVE_HR_POSITION:
          WAREHOUSE_SAVE_HR_POSITION ?? this.WAREHOUSE_SAVE_HR_POSITION,
      WAREHOUSE_SAVE_HR_DEP_SUB_NAME:
          WAREHOUSE_SAVE_HR_DEP_SUB_NAME ?? this.WAREHOUSE_SAVE_HR_DEP_SUB_NAME,
      WAREHOUSE_STATUS: WAREHOUSE_STATUS ?? this.WAREHOUSE_STATUS,
      WAREHOUSE_AGREE_HR_ID:
          WAREHOUSE_AGREE_HR_ID ?? this.WAREHOUSE_AGREE_HR_ID,
      WAREHOUSE_AGREE_HR_NAME:
          WAREHOUSE_AGREE_HR_NAME ?? this.WAREHOUSE_AGREE_HR_NAME,
      WAREHOUSE_REQUEST_BUY_COMMENT:
          WAREHOUSE_REQUEST_BUY_COMMENT ?? this.WAREHOUSE_REQUEST_BUY_COMMENT,
      WAREHOUSE_BUDGET_YEAR:
          WAREHOUSE_BUDGET_YEAR ?? this.WAREHOUSE_BUDGET_YEAR,
      WAREHOUSE_INVEN_ID: WAREHOUSE_INVEN_ID ?? this.WAREHOUSE_INVEN_ID,
      INVEN_NAME: INVEN_NAME ?? this.INVEN_NAME,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'WAREHOUSE_ID': WAREHOUSE_ID,
      'WAREHOUSE_REQUEST_CODE': WAREHOUSE_REQUEST_CODE,
      'WAREHOUSE_DATE_WANT': WAREHOUSE_DATE_WANT,
      'WAREHOUSE_SAVE_HR_ID': WAREHOUSE_SAVE_HR_ID,
      'WAREHOUSE_SAVE_HR_NAME': WAREHOUSE_SAVE_HR_NAME,
      'WAREHOUSE_SAVE_HR_POSITION': WAREHOUSE_SAVE_HR_POSITION,
      'WAREHOUSE_SAVE_HR_DEP_SUB_NAME': WAREHOUSE_SAVE_HR_DEP_SUB_NAME,
      'WAREHOUSE_STATUS': WAREHOUSE_STATUS,
      'WAREHOUSE_AGREE_HR_ID': WAREHOUSE_AGREE_HR_ID,
      'WAREHOUSE_AGREE_HR_NAME': WAREHOUSE_AGREE_HR_NAME,
      'WAREHOUSE_REQUEST_BUY_COMMENT': WAREHOUSE_REQUEST_BUY_COMMENT,
      'WAREHOUSE_BUDGET_YEAR': WAREHOUSE_BUDGET_YEAR,
      'WAREHOUSE_INVEN_ID': WAREHOUSE_INVEN_ID,
      'INVEN_NAME': INVEN_NAME,
    };
  }

  factory WarehouseModel.fromMap(Map<String, dynamic> map) {
    return WarehouseModel(
      WAREHOUSE_ID: map['WAREHOUSE_ID'] == null ? '' : map['WAREHOUSE_ID'],
      WAREHOUSE_REQUEST_CODE: map['WAREHOUSE_REQUEST_CODE'] == null
          ? ''
          : map['WAREHOUSE_REQUEST_CODE'],

      WAREHOUSE_DATE_WANT:
          map['WAREHOUSE_DATE_WANT'] == null ? '' : map['WAREHOUSE_DATE_WANT'],

      WAREHOUSE_SAVE_HR_ID: map['WAREHOUSE_SAVE_HR_ID'] == null
          ? ''
          : map['WAREHOUSE_SAVE_HR_ID'],

      WAREHOUSE_SAVE_HR_NAME: map['WAREHOUSE_SAVE_HR_NAME'] == null
          ? ''
          : map['WAREHOUSE_SAVE_HR_NAME'],

      WAREHOUSE_SAVE_HR_POSITION: map['WAREHOUSE_SAVE_HR_POSITION'] == null
          ? ''
          : map['WAREHOUSE_SAVE_HR_POSITION'],

      WAREHOUSE_SAVE_HR_DEP_SUB_NAME:
          map['WAREHOUSE_SAVE_HR_DEP_SUB_NAME'] == null
              ? ''
              : map['WAREHOUSE_SAVE_HR_DEP_SUB_NAME'],

      WAREHOUSE_STATUS:
          map['WAREHOUSE_STATUS'] == null ? '' : map['WAREHOUSE_STATUS'],

      WAREHOUSE_AGREE_HR_ID: map['WAREHOUSE_AGREE_HR_ID'] == null
          ? ''
          : map['WAREHOUSE_AGREE_HR_ID'],

      WAREHOUSE_AGREE_HR_NAME: map['WAREHOUSE_AGREE_HR_NAME'] == null
          ? ''
          : map['WAREHOUSE_AGREE_HR_NAME'],

      WAREHOUSE_REQUEST_BUY_COMMENT:
          map['WAREHOUSE_REQUEST_BUY_COMMENT'] == null
              ? ''
              : map['WAREHOUSE_REQUEST_BUY_COMMENT'],

      WAREHOUSE_BUDGET_YEAR: map['WAREHOUSE_BUDGET_YEAR'] == null
          ? ''
          : map['WAREHOUSE_BUDGET_YEAR'],

      WAREHOUSE_INVEN_ID:
          map['WAREHOUSE_INVEN_ID'] == null ? '' : map['WAREHOUSE_INVEN_ID'],

      INVEN_NAME: map['INVEN_NAME'] == null ? '' : map['INVEN_NAME'],
    );
  }

  String toJson() => json.encode(toMap());

  factory WarehouseModel.fromJson(String source) =>
      WarehouseModel.fromMap(json.decode(source));

  @override
  String toString() {
    return 'WarehouseModel(WAREHOUSE_ID: $WAREHOUSE_ID, WAREHOUSE_REQUEST_CODE: $WAREHOUSE_REQUEST_CODE, WAREHOUSE_DATE_WANT: $WAREHOUSE_DATE_WANT, WAREHOUSE_SAVE_HR_ID: $WAREHOUSE_SAVE_HR_ID, WAREHOUSE_SAVE_HR_NAME: $WAREHOUSE_SAVE_HR_NAME, WAREHOUSE_SAVE_HR_POSITION: $WAREHOUSE_SAVE_HR_POSITION, WAREHOUSE_SAVE_HR_DEP_SUB_NAME: $WAREHOUSE_SAVE_HR_DEP_SUB_NAME, WAREHOUSE_STATUS: $WAREHOUSE_STATUS, WAREHOUSE_AGREE_HR_ID: $WAREHOUSE_AGREE_HR_ID, WAREHOUSE_AGREE_HR_NAME: $WAREHOUSE_AGREE_HR_NAME, WAREHOUSE_REQUEST_BUY_COMMENT: $WAREHOUSE_REQUEST_BUY_COMMENT, WAREHOUSE_BUDGET_YEAR: $WAREHOUSE_BUDGET_YEAR, WAREHOUSE_INVEN_ID: $WAREHOUSE_INVEN_ID,INVEN_NAME:$INVEN_NAME)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is WarehouseModel &&
        other.WAREHOUSE_ID == WAREHOUSE_ID &&
        other.WAREHOUSE_REQUEST_CODE == WAREHOUSE_REQUEST_CODE &&
        other.WAREHOUSE_DATE_WANT == WAREHOUSE_DATE_WANT &&
        other.WAREHOUSE_SAVE_HR_ID == WAREHOUSE_SAVE_HR_ID &&
        other.WAREHOUSE_SAVE_HR_NAME == WAREHOUSE_SAVE_HR_NAME &&
        other.WAREHOUSE_SAVE_HR_POSITION == WAREHOUSE_SAVE_HR_POSITION &&
        other.WAREHOUSE_SAVE_HR_DEP_SUB_NAME ==
            WAREHOUSE_SAVE_HR_DEP_SUB_NAME &&
        other.WAREHOUSE_STATUS == WAREHOUSE_STATUS &&
        other.WAREHOUSE_AGREE_HR_ID == WAREHOUSE_AGREE_HR_ID &&
        other.WAREHOUSE_AGREE_HR_NAME == WAREHOUSE_AGREE_HR_NAME &&
        other.WAREHOUSE_REQUEST_BUY_COMMENT == WAREHOUSE_REQUEST_BUY_COMMENT &&
        other.WAREHOUSE_BUDGET_YEAR == WAREHOUSE_BUDGET_YEAR &&
        other.WAREHOUSE_INVEN_ID == WAREHOUSE_INVEN_ID &&
        other.INVEN_NAME == INVEN_NAME;
  }

  @override
  int get hashCode {
    return WAREHOUSE_ID.hashCode ^
        WAREHOUSE_REQUEST_CODE.hashCode ^
        WAREHOUSE_DATE_WANT.hashCode ^
        WAREHOUSE_SAVE_HR_ID.hashCode ^
        WAREHOUSE_SAVE_HR_NAME.hashCode ^
        WAREHOUSE_SAVE_HR_POSITION.hashCode ^
        WAREHOUSE_SAVE_HR_DEP_SUB_NAME.hashCode ^
        WAREHOUSE_STATUS.hashCode ^
        WAREHOUSE_AGREE_HR_ID.hashCode ^
        WAREHOUSE_AGREE_HR_NAME.hashCode ^
        WAREHOUSE_REQUEST_BUY_COMMENT.hashCode ^
        WAREHOUSE_BUDGET_YEAR.hashCode ^
        WAREHOUSE_INVEN_ID.hashCode ^
        INVEN_NAME.hashCode;
  }
}
